"""Deterministic synthetic-data generator -> db/02_seed.sql.

Run once to (re)generate the seed file that the postgres container loads at
init. Output is committed to the repo, so the database is fully reproducible
without running Python at container start.

    uv run --extra seed python scripts/generate_seed.py

Deterministic: a fixed RNG seed means the same data every run, so analytics
answers (and any tests over them) are stable.

Fully implemented.
"""

from __future__ import annotations

import random
from datetime import date, timedelta
from pathlib import Path

from faker import Faker

SEED = 42
OUTPUT = Path(__file__).resolve().parent.parent / "db" / "02_seed.sql"

# Volumes — tuned to be rich but to keep the seed file and load time reasonable.
N_CUSTOMERS = 2_000
N_SUPPLIERS = 60
N_PRODUCTS = 250
N_ORDERS = 9_000

START_DATE = date(2022, 1, 1)
END_DATE = date(2024, 12, 31)

REGIONS = ["North America", "South America", "Europe", "Asia", "Africa", "Oceania"]

# (country, iso2, region)
COUNTRIES = [
    ("United States", "US", "North America"), ("Canada", "CA", "North America"),
    ("Mexico", "MX", "North America"), ("Brazil", "BR", "South America"),
    ("Argentina", "AR", "South America"), ("Chile", "CL", "South America"),
    ("Colombia", "CO", "South America"), ("United Kingdom", "GB", "Europe"),
    ("Germany", "DE", "Europe"), ("France", "FR", "Europe"),
    ("Spain", "ES", "Europe"), ("Italy", "IT", "Europe"),
    ("Netherlands", "NL", "Europe"), ("Sweden", "SE", "Europe"),
    ("Poland", "PL", "Europe"), ("Portugal", "PT", "Europe"),
    ("China", "CN", "Asia"), ("Japan", "JP", "Asia"),
    ("India", "IN", "Asia"), ("South Korea", "KR", "Asia"),
    ("Singapore", "SG", "Asia"), ("Indonesia", "ID", "Asia"),
    ("Turkey", "TR", "Asia"), ("Israel", "IL", "Asia"),
    ("Egypt", "EG", "Africa"), ("Nigeria", "NG", "Africa"),
    ("South Africa", "ZA", "Africa"), ("Kenya", "KE", "Africa"),
    ("Morocco", "MA", "Africa"), ("Australia", "AU", "Oceania"),
    ("New Zealand", "NZ", "Oceania"),
]

# (category, parent or None)
CATEGORIES = [
    ("Electronics", None), ("Computers", "Electronics"), ("Phones", "Electronics"),
    ("Audio", "Electronics"), ("Home", None), ("Kitchen", "Home"),
    ("Furniture", "Home"), ("Lighting", "Home"), ("Apparel", None),
    ("Men", "Apparel"), ("Women", "Apparel"), ("Footwear", "Apparel"),
    ("Sports", None), ("Outdoors", "Sports"), ("Fitness", "Sports"),
    ("Books", None), ("Fiction", "Books"), ("Technical", "Books"),
    ("Toys", None), ("Beauty", None),
]

SEGMENTS = ["consumer", "consumer", "consumer", "business", "business", "enterprise"]
ORDER_STATUSES = ["completed", "completed", "completed", "completed",
                  "pending", "cancelled", "refunded"]
CHANNELS = ["web", "web", "web", "mobile", "mobile", "store", "partner"]
PAY_METHODS = ["card", "card", "card", "paypal", "bank_transfer", "crypto"]

fake = Faker()


def esc(value: str) -> str:
    """Escape a string for a single-quoted SQL literal."""
    return value.replace("'", "''")


def random_date(rng: random.Random, start: date, end: date) -> date:
    return start + timedelta(days=rng.randint(0, (end - start).days))


def main() -> None:
    rng = random.Random(SEED)
    Faker.seed(SEED)

    lines: list[str] = [
        "-- Generated by scripts/generate_seed.py — do not edit by hand.",
        "BEGIN;",
    ]

    # regions
    region_id = {name: i + 1 for i, name in enumerate(REGIONS)}
    values = ", ".join(f"({i + 1}, '{esc(n)}')" for i, n in enumerate(REGIONS))
    lines.append(f"INSERT INTO regions (region_id, name) VALUES {values};")

    # countries
    country_rows = []
    for i, (name, iso, region) in enumerate(COUNTRIES, start=1):
        country_rows.append(f"({i}, '{esc(name)}', '{iso}', {region_id[region]})")
    lines.append(
        "INSERT INTO countries (country_id, name, iso_code, region_id) VALUES "
        + ", ".join(country_rows)
        + ";"
    )
    n_countries = len(COUNTRIES)

    # categories (two passes so parents exist)
    cat_id = {name: i + 1 for i, (name, _) in enumerate(CATEGORIES)}
    cat_rows = []
    for i, (name, parent) in enumerate(CATEGORIES, start=1):
        parent_sql = str(cat_id[parent]) if parent else "NULL"
        cat_rows.append(f"({i}, '{esc(name)}', {parent_sql})")
    lines.append(
        "INSERT INTO categories (category_id, name, parent_category_id) VALUES "
        + ", ".join(cat_rows)
        + ";"
    )
    n_categories = len(CATEGORIES)

    # suppliers
    sup_rows = []
    for i in range(1, N_SUPPLIERS + 1):
        sup_rows.append(f"({i}, '{esc(fake.company())}', {rng.randint(1, n_countries)})")
    lines.append(
        "INSERT INTO suppliers (supplier_id, name, country_id) VALUES "
        + ", ".join(sup_rows)
        + ";"
    )

    # products (leaf categories preferred = those that are someone's... just use all)
    prod_rows = []
    for i in range(1, N_PRODUCTS + 1):
        cost = round(rng.uniform(2, 800), 2)
        price = round(cost * rng.uniform(1.15, 2.5), 2)
        active = "TRUE" if rng.random() > 0.1 else "FALSE"
        name = esc(f"{fake.color_name()} {fake.word().capitalize()} {rng.randint(100, 999)}")
        prod_rows.append(
            f"({i}, '{name}', {rng.randint(1, n_categories)}, "
            f"{rng.randint(1, N_SUPPLIERS)}, {price}, {cost}, {active})"
        )
    lines.append(
        "INSERT INTO products "
        "(product_id, name, category_id, supplier_id, unit_price, cost, is_active) VALUES "
        + ", ".join(prod_rows)
        + ";"
    )

    # customers
    cust_rows = []
    used_emails: set[str] = set()
    for i in range(1, N_CUSTOMERS + 1):
        name = fake.name()
        email = fake.unique.email()
        used_emails.add(email)
        cust_rows.append(
            f"({i}, '{esc(name)}', '{esc(email)}', {rng.randint(1, n_countries)}, "
            f"'{rng.choice(SEGMENTS)}', '{random_date(rng, START_DATE, END_DATE)}')"
        )
    lines.append(
        "INSERT INTO customers "
        "(customer_id, full_name, email, country_id, segment, signup_date) VALUES "
        + ", ".join(cust_rows)
        + ";"
    )

    # orders + order_items + payments
    order_rows: list[str] = []
    item_rows: list[str] = []
    payment_rows: list[str] = []
    item_id = 0
    payment_id = 0
    # cache product prices for order_items / payment totals
    # (regenerate deterministically: rebuild the same product price list)
    prod_prices: dict[int, float] = {}
    rng2 = random.Random(SEED)
    for i in range(1, N_PRODUCTS + 1):
        cost = round(rng2.uniform(2, 800), 2)
        prod_prices[i] = round(cost * rng2.uniform(1.15, 2.5), 2)

    for order_id in range(1, N_ORDERS + 1):
        customer_id = rng.randint(1, N_CUSTOMERS)
        odate = random_date(rng, START_DATE, END_DATE)
        status = rng.choice(ORDER_STATUSES)
        channel = rng.choice(CHANNELS)
        order_rows.append(
            f"({order_id}, {customer_id}, '{odate}', '{status}', '{channel}')"
        )

        n_items = rng.randint(1, 5)
        order_total = 0.0
        for _ in range(n_items):
            item_id += 1
            product_id = rng.randint(1, N_PRODUCTS)
            qty = rng.randint(1, 6)
            unit_price = prod_prices[product_id]
            discount = rng.choice([0, 0, 0, 0.05, 0.1, 0.15, 0.2])
            item_rows.append(
                f"({item_id}, {order_id}, {product_id}, {qty}, {unit_price}, {discount})"
            )
            order_total += qty * unit_price * (1 - discount)

        # payment(s): completed/refunded orders are captured/refunded; others may fail
        if status in ("completed", "refunded"):
            payment_id += 1
            pstatus = "refunded" if status == "refunded" else "captured"
            payment_rows.append(
                f"({payment_id}, {order_id}, {round(order_total, 2)}, '{odate}', "
                f"'{rng.choice(PAY_METHODS)}', '{pstatus}')"
            )
        elif status == "pending" and rng.random() < 0.5:
            payment_id += 1
            payment_rows.append(
                f"({payment_id}, {order_id}, {round(order_total, 2)}, '{odate}', "
                f"'{rng.choice(PAY_METHODS)}', 'failed')"
            )

    _emit_bulk(lines, "orders",
               "order_id, customer_id, order_date, status, channel", order_rows)
    _emit_bulk(lines, "order_items",
               "order_item_id, order_id, product_id, quantity, unit_price, discount", item_rows)
    _emit_bulk(lines, "payments",
               "payment_id, order_id, amount, payment_date, method, status", payment_rows)

    # reviews
    review_rows: list[str] = []
    review_id = 0
    for _ in range(N_ORDERS // 3):
        review_id += 1
        review_rows.append(
            f"({review_id}, {rng.randint(1, N_PRODUCTS)}, {rng.randint(1, N_CUSTOMERS)}, "
            f"{rng.choices([1, 2, 3, 4, 5], weights=[1, 1, 2, 4, 5])[0]}, "
            f"'{random_date(rng, START_DATE, END_DATE)}')"
        )
    _emit_bulk(lines, "reviews",
               "review_id, product_id, customer_id, rating, review_date", review_rows)

    # reset sequences so future manual inserts don't collide
    for table, col in [
        ("regions", "region_id"), ("countries", "country_id"),
        ("categories", "category_id"), ("suppliers", "supplier_id"),
        ("products", "product_id"), ("customers", "customer_id"),
        ("orders", "order_id"), ("order_items", "order_item_id"),
        ("payments", "payment_id"), ("reviews", "review_id"),
    ]:
        lines.append(
            f"SELECT setval(pg_get_serial_sequence('{table}', '{col}'), "
            f"(SELECT MAX({col}) FROM {table}));"
        )

    lines.append("COMMIT;")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size // 1024} KiB)")


def _emit_bulk(lines: list[str], table: str, columns: str, rows: list[str]) -> None:
    """Emit chunked multi-row INSERTs (chunked to keep statements parseable)."""
    chunk = 500
    for start in range(0, len(rows), chunk):
        batch = rows[start:start + chunk]
        lines.append(f"INSERT INTO {table} ({columns}) VALUES " + ", ".join(batch) + ";")


if __name__ == "__main__":
    main()
